spring:

  application:
    name: mentorbridge-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mentoring_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 서버 재시작 시 데이터가 날아가지 않도록 update로 변경합니다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (1일)

server:
  port: 8080
